### ISSUE TITLE
[BUG] Impossibilità di interagire con personagge a scena iniziale finita

### ISSUE THREAD

**Issue by LupettoLavoretto** [owof-games/progettoa-proto4#1]
![Cattura](https://github.com/user-attachments/assets/1f4f1639-c4d6-472b-8bb3-8fbc25156f0e)

Windows

1. Finisco la scena iniziale
2. Escono tutti dalla stanza
3. Clicco Greta
4. Non posso più interagire con nulla

**Comment by RedGlow** [comment]
@LupettoLavoretto puoi fare un check se questo bug si presenta ancora?

**Comment by LupettoLavoretto** [comment]
Ho fatto qualche giro prima e il problema non si è più presentato <3
