### ISSUE TITLE
Testo straborda dal box

### ISSUE THREAD

**Issue by LupettoLavoretto** [owof-games/progettoa-proto4#2]
Primo dialogo, solo avanzamento, nient'altro di particolare, build aggiornata
![image](https://github.com/user-attachments/assets/0ec93553-838a-47cd-87a9-7b85e5baf1f3)
****

**Comment by RedGlow** [comment]
@LupettoLavoretto fai un check sulla 0.0.10! adesso tutti i balloon sono sempre girati nello stesso verso per il discorso che abbiamo fatto domenica.
(se vedi difetti grafici che esistono ma non sono questo, apri un ticket diverso!)

**Comment by LupettoLavoretto** [comment]
problema non più presentato con la nuova versione :D
