### ISSUE TITLE
Bug durante utilizzo tasto "avanza tempo"

### ISSUE THREAD

**Issue by LupettoLavoretto** [owof-games/progettoa-proto4#3]
![image](https://github.com/user-attachments/assets/1b98c350-41cc-4159-9d10-b83253df3ae8)
Ultima versione

**Comment by RedGlow** [comment]
@LupettoLavoretto il problema è che il testo di avanzamento della scelte di tempo dev'essere quello indicato nell'errore ("debug:advance_time"); se intanto provi a cambiare il file ink, faccio una nuova versione!

PS: indica sempre il numero di versione, perché poi c'e richio che ci si torna sopra dopo due o tre settimane e non sappiamo più qual è la "ultima versione"! :)

**Comment by LupettoLavoretto** [comment]
Aggiornato ink (se ho inteso bene, ho fatto come per tutte le altre etichette usate per unity come character o object, e ho fatto un + [debug: advance_time], giusto?

**Comment by RedGlow** [comment]
@LupettoLavoretto fai un check sulla 0.0.10! ho corretto "[debug: advance_time]" in "[debug:advance_time]" (senza spazio).

**Comment by LupettoLavoretto** [comment]
Funge <3
