### ISSUE TITLE
[BUG] i personaggi si possono allontanare durante la conversazione

### ISSUE THREAD

**Issue by LupettoLavoretto** [owof-games/progettoa-proto4#4]
**Versione**: ...
Versione v0.0.9

**Sistema**: ...
Windows

**Descrivi il bug**
Durante la conversazione i personaggi si allontanano.
Il perché dipende da com'è strutturato il codice ink (-> advance_time -> ogni 8 righe richiama ~ updateEntitiesLocations()), è da capire come vogliamo agire su questa cosa.

![Uploading matteo se ne è andato ma parla ancora.PNG…]()

**Comment by LupettoLavoretto** [comment]
![perché matteo se ne va](https://github.com/user-attachments/assets/013ec0b2-567b-444d-bdb2-6a358d742c49)
![deve dirlo matteo](https://github.com/user-attachments/assets/9211e2a0-c2ef-4e0e-8379-a90ee6b5f45e)

provo a ricaricare le foto perché forse sopra ha avuto un problema

**Comment by RedGlow** [comment]
"Finalmente soli"
davvero MOLTO soli!

**Comment by RedGlow** [comment]
@LupettoLavoretto questo problema l'abbiamo risolto adesso, giusto?

**Comment by LupettoLavoretto** [comment]
Yup

**Comment by LupettoLavoretto** [comment]
chiuso
